apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: moodle
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: frontend
    spec:
      containers:
      - image: jhardison/moodle
        name: moodle
        env:
        - name: DB_PORT_3306_TCP_ADDR
          valueFrom:
            secretKeyRef:
              name: moodle-db-server
              key: moodle-db-host
        - name: DB_ENV_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodle-db-uname
              key: moodle-db-username
        - name: DB_ENV_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: moodle-db-pw
              key: moodle-db-password
        - name: DB_ENV_MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: moodle-db
              key: moodle-db-name
        - name: MOODLE_URL
          value: http://localhost
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: moodle-persistent-storage
          mountPath: /var/moodledata
      volumes:
      - name: moodle-persistent-storage
        persistentVolumeClaim:
          claimName: moodle-pv-claim
